create table if not exists public.users (
  id bigint generated by default as identity primary key,
  email text not null unique,
  "passwordHash" text not null,
  "createdAt" timestamptz default now()
);

create table if not exists public.notes (
  id bigint generated by default as identity primary key,
  "userId" bigint references public.users(id) on delete cascade,
  title text default '',
  text text default '',
  "canvasJson" jsonb default '{}'::jsonb,
  "audioUrl" text,
  tags jsonb default '[]'::jsonb,
  "createdAt" timestamptz default now(),
  "updatedAt" timestamptz default now()
);

create index if not exists idx_notes_user_id on public.notes("userId");
create index if not exists idx_notes_updated_at on public.notes("updatedAt" desc);
